version: 2.0
jobs:
  acceptance:
    docker:
      - image: circleci/node:8-stretch-browsers
    parallelism: 1
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Acceptance Tests
          command: "yarn install && yarn acceptance src/test/acceptance/*.js"
  test:
    docker:
      - image: artsy/hokusai:0.4.0
    parallelism: 4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: "hokusai test"
  build:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - run:
          name: "OK"
          command: "echo All Tests Pass!"
  push:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  deploy_hokusai_staging:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Build Assets
          command: hokusai dev run 'yarn publish_assets'
      - run:
          name: Asset Manifest
          command: hokusai staging env set ASSET_MANIFEST=$(cat manifest.json)
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1
  deploy_hokusai_production:
    docker:
      - image: artsy/hokusai:0.4.0
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Build Assets
          command: hokusai dev run 'yarn publish_assets'
      - run:
          name: Asset Manifest
          command: hokusai production env set ASSET_MANIFEST=$(cat manifest.json)
      - run:
          name: Deploy
          command: hokusai production deploy $CIRCLE_SHA1

workflows:
  version: 2
  default:
    jobs:
      - test:
          filters:
            branches:
              ignore: staging
      - acceptance:
          filters:
            branches:
              ignore: staging
      - build:
          filters:
            branches:
              ignore: staging
          requires:
            - test
            - acceptance
      - push:
          filters:
            branches:
              only:
                - master
                - release
          requires:
            - build
      - deploy_hokusai_staging:
          filters:
            branches:
              only: master
          requires:
            - push
            - deploy_heroku_staging
      - deploy_hokusai_production:
          filters:
            branches:
              only: release
          requires:
            - push
            - deploy_heroku_production
      - deploy_heroku_staging:
          filters:
            branches:
              only: master
          requires:
            - test
            - acceptance
      - deploy_heroku_production:
          filters:
            branches:
              only: release
          requires:
            - test
            - acceptance
