version: 2.0
jobs:
  acceptance:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Acceptance Tests
          command: "yarn install && yarn acceptance src/test/acceptance/*.js"
  test:
    docker:
      - image: artsy/hokusai:0.4.5
    parallelism: 4
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: |
            hokusai test
  validate_staging_schema:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Validate Staging Schema
          command: "yarn install && node scripts/validateSchemas.js staging"
  validate_production_schema:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Validate Production Schema
          command: "yarn install && node scripts/validateSchemas.js production"
  push_staging_image: &push_image
    docker:
      - image: artsy/hokusai:0.4.5
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run:
          name: Push
          command: |
            hokusai registry push --tag $CIRCLE_SHA1 --force --overwrite
  push_production_image: *push_image
  publish_staging_assets:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: yarn install && DEPLOY_ENV=staging yarn publish-assets
      - run: mkdir -p workspace
      - run: cp manifest.json workspace/manifest.json
      - persist_to_workspace:
          root: workspace
          paths:
            - manifest.json
  publish_production_assets:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: yarn install && DEPLOY_ENV=production yarn publish-assets
      - run: mkdir -p workspace
      - run: cp manifest.json workspace/manifest.json
      - persist_to_workspace:
          root: workspace
          paths:
            - manifest.json
  deploy_hokusai_staging:
    docker:
      - image: artsy/hokusai:0.4.5
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Echo Manifest
          command: cat /tmp/workspace/manifest.json
      - run:
          name: Update staging branch
          command: git push git@github.com:artsy/force.git $CIRCLE_SHA1:staging --force
      - run:
          name: Deploy
          command: hokusai staging deploy $CIRCLE_SHA1
  deploy_hokusai_production:
    docker:
      - image: artsy/hokusai:0.4.5
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Echo Manifest
          command: cat /tmp/workspace/manifest.json
      - run:
          name: Configure
          command: hokusai configure --kubectl-version 1.6.3 --s3-bucket artsy-citadel --s3-key k8s/config --platform linux
      - run:
          name: Deploy
          command: hokusai production deploy $CIRCLE_SHA1 --git-remote origin

workflows:
  version: 2
  default:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - staging
                - release
      - acceptance:
          filters:
            branches:
              ignore:
                - staging
                - release
      - validate_staging_schema:
          filters:
            branches:
              ignore:
                - staging
                - release
      - validate_production_schema:
          filters:
            branches:
              only: release
      - push_staging_image:
          filters:
            branches:
              only: master
          requires:
            - test
            - acceptance
            - validate_staging_schema
      - push_production_image:
          filters:
            branches:
              only: release
          requires:
            - validate_production_schema
      - publish_staging_assets:
          filters:
            branches:
              only: master
          requires:
            - test
            - acceptance
            - validate_staging_schema
      - publish_production_assets:
          filters:
            branches:
              only: release
          requires:
            - validate_production_schema
      - deploy_hokusai_staging:
          filters:
            branches:
              only: master
          requires:
            - push_staging_image
            - publish_staging_assets
      - deploy_hokusai_production:
          filters:
            branches:
              only: release
          requires:
            - push_production_image
            - publish_production_assets
