---
aws-account-id: "585031190124"
aws-ecr-region: us-east-1
project-name: force
post-deploy: 'title="Force was deployed"; text="force was deployed"; echo -e "_e{${#title},${#text}}:$title|$text|#service:force" > /dev/udp/datadog/8125'
